### ISSUE TITLE
Consult

### ISSUE THREAD

**Issue by B1SH0PP** [hamhanry/YOLOv10-OBB#1]
Hello, I am glad to see your project!
I directly applied the obb module of v8, the model scale is `s`, but I only can get 48 map@50 (test) on dotav1.
Can I ask you which parts of the network your obb module changed?
![image](https://github.com/hamhanry/YOLOv10-OBB/assets/79520631/af688017-e2e5-42df-bd4a-07454bb483f1)

**Comment by hamhanry** [comment]
Hi @B1SH0PP 
to be honest, i ever tried to reproduced that ultralytics pretrained model that used V8-n.
However my results is not comparable to what is written here https://docs.ultralytics.com/tasks/obb/#visual-samples
My v8n achieved mAP50: 0.602 with image_size 1024 (this used their pretrained v8-n)

I changed the last config layer where as before used v10detect, changed it to OBB module there.

**Comment by B1SH0PP** [comment]
The map indicator given by ultralytics does not seem to be the test result of the test data set. (At least when I directly use its weight test result, it is only more than 50)
http://[bed4rs.net:8001/evaluation1/](http://bed4rs.net:8001/evaluation1/)

This is the test score of v8m I tested:
![image](https://github.com/hamhanry/YOLOv10-OBB/assets/79520631/1233e318-8c8f-4e22-a560-522320f412ac)

**Comment by hamhanry** [comment]
I beleive the results in their table is not taken directly from the test set of the given DOTAv1 test. It is describe in the web that, they submitted the inference results to the [DOTA evaluation server ](https://captain-whu.github.io/DOTA/evaluation.html).

![image](https://github.com/hamhanry/YOLOv10-OBB/assets/28456630/1fe1ceca-96f1-42ca-917e-e04f261415ff)
