### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by russel0719** [hamhanry/YOLOv10-OBB#2]
Hi, Thank you for your great work!

I want to train this YOLOv10-OBB model on my own custom dataset.
So, is there a plan for releasing training code?

Thanks

**Comment by hamhanry** [comment]
Hi @russel0719 ,
actually the training code can use from the ultralytics pipeline.
more or less the same with the yolov8 guideline [here](https://docs.ultralytics.com/tasks/obb/#models)

As the training configuration is described within the ckpt it self, the ultralytics trainer automatically recognized it without any pre-made script.

So just picked any of my pretrained model

```
model = YOLO("yolov10n-obb.pt")
results = model.train(data="your_training_data.yaml", epochs=100, imgsz=640)
```

**Comment by russel0719** [comment]
Thank you for your reply!

I thought that I need both `model.yaml` file and `data.yaml` file to train. If there is a pre-trained checkpoint file, only `data.yaml` file is needed.
Thank you for your kind explanation.
I'll try it!
