### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by liu15509348793** [hamhanry/YOLOv10-OBB#3]
Hello, thank you for your work, I would like to know where to get the source code

**Comment by hamhanry** [comment]
hi @liu15509348793 
the training code were based on the ultralytics version. (pleaes check the environment that i put in this repo)
as long as you follow the rquiremend and my snippet code, you could just train directly.

**Comment by hamhanry** [comment]
@liu15509348793 please check this https://github.com/hamhanry/YOLOv10-OBB/issues/4#issuecomment-2270345019
