### ISSUE TITLE
OBB Error

### ISSUE THREAD

**Issue by ardamollakoy** [hamhanry/YOLOv10-OBB#6]
Hi. Thank you very much for your work. I want to use your pretrained OBB model on my own dataset, and download "YOLOv10-N-OBB". But, i get an error like  "NotImplementedError: WARNING  'YOLOv10' model does not support 'train' mode for 'obb' task yet.". Do you have any idea what is causing this issue?

**Comment by hamhanry** [comment]
hi @ardamollakoy 
could you check your ultralytics version?
this pretrained were trained using version 8.2.49
and as of today, there is a PR for updating the latest version of it.

**Comment by Cyeden** [comment]
@ardamollakoy hi bro，I have the same problem as you, have you solved it? Thanks！:D
